name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build and Publish Release
    runs-on: ubuntu-latest
    permissions:
      contents: write    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      - name: Cache Go modules
        uses: actions/cache@v6
        with:
          path: |
            ~/.cache/go-build
            ${{ env.GOMODCACHE }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Build all binary
        run: |
          make distribution
          # GOOS=linux GOARCH=amd64 go build -o release/docker-base-watch-linux-amd64 .

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            distribution/docker-base-watch-linux-amd64
            distribution/docker-base-watch-linux-arm64
            distribution/docker-base-watch-windows-amd64.exe
          body: |
            Release ${{ github.ref_name }} of docker-base-watch.
          draft: false
          prerelease: false
          overwrite_files: true
          generate_release_notes: true
